<?php

namespace frontend\controllers;

use Yii;
use yii\helpers\Url;
use yii\web\Controller;

abstract class Base18oldController extends Controller
{

    public function beforeAction($action)
    {
        $cookie = Yii::$app->request->cookies;
//        Yii::$app->response->cookies->add(new \yii\web\Cookie([
//            'name' => '18old',
//            'value' => 'yes',
//        ]));
        if (!empty($cookie->get('18old') && $cookie->get('18old')->value === 'no' && Yii::$app->controller->action->id !== 'has18-fail')) {
            return $this->redirect(Url::toRoute('/site/has18-fail'))->send();
        }
        if (empty($cookie->get('18old')) &&
            Yii::$app->controller->action->id !== 'has18' &&
            $cookie->get('18old')->value !== 'yes') {
            return $this->redirect(Url::toRoute('/site/has18'))->send();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}
